project:
  type: website

website:
  title: "Calson's Portfolio"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: fyp.qmd
        text: FYP Project
      - href: dataviz.qmd
        text: Data Visualization
      - href: hobbies.qmd
        text: Hobbies & Interests
      - href: reflection.qmd
        text: GenAI Reflection

format:
  html:
    theme: slate
    fontcolor: white
    backgroundcolor: "#272b30"
    toc: false